version: '3.8'

services:
  db:
    image: postgres:15
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_DB=finance_tracker
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  web:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    environment:
      - DEBUG=1
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/finance_tracker
      - SECRET_KEY=your-secret-key-here-change-in-production

  cron:
    build: .
    command: cron -f
    volumes:
      - .:/app
    depends_on:
      web:
        condition: service_started
    environment:
      - DATABASE_URL=postgresql://postgres:postgres123@db:5432/finance_tracker
      - SECRET_KEY=your-secret-key-here-change-in-production

volumes:
  postgres_data: